version: '3.8'
services:
  scylla:
    image: scylladb/scylla
    container_name: test-scylla
    networks:
      scylla-net:
        ipv4_address: 172.21.0.2
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
    volumes:
      - ./data:/var/lib/scylla

networks:
  scylla-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
